# Generated by Django 5.0.7 on 2024-07-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=15, unique=True)),
                ('player_count', models.IntegerField(default=0)),
                ('coach_name', models.CharField(default='None', max_length=25)),
                ('goals_scored', models.IntegerField(default=0, max_length=1000)),
            ],
        ),
    ]
