# Generated by Django 5.0.7 on 2024-07-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='coach_name',
            field=models.CharField(default='none', max_length=25),
        ),
        migrations.AlterField(
            model_name='team',
            name='goals_scored',
            field=models.IntegerField(default=0),
        ),
    ]
